---
- hosts: localhost
  tasks:
    - name: Ensure alacritty apt repo is present
      apt_repository:
        repo: 'ppa:mmstick76/alacritty'
        state: present
      become: yes

    - name: Install alacritty
      apt:
        name: alacritty
      become: yes

    - name: Check for old .alacritty.yml
      stat:
        path: ~/.config/alacritty/alacritty.yml
      register: old_yml

    - name: Copy old .alacritty.yml
      copy:
        src: ~/.config/alacritty/alacritty.yml
        dest: "{{ playbook_dir }}/../backups/alacritty.yml"
      when: (old_yml.stat.exists == True) and (old_yml.stat.islnk == False)

    - name: Delete old .alacritty.yml
      file:
        dest: ~/.config/alacritty/alacritty.yml
        state: absent
      when: (old_yml.stat.exists == True) and (old_yml.stat.islnk == False)

    - name: Creates alacritty config directory
      file:
        path: "~/.config/alacritty"
        state: directory

    - name: Create .alacritty Symlink
      file:
        src: "{{ playbook_dir }}/alacritty.yml"
        dest: ~/.config/alacritty/alacritty.yml
        state: link
