---
- hosts: localhost
  tasks:
    - name: Creates backup directory
      file:
        path: "{{ playbook_dir }}/backups"
        state: directory

- import_playbook: alacritty/playbook.yml
- import_playbook: bash/playbook.yml
# - import_playbook: exa/playbook.yml
- import_playbook: fzf/playbook.yml
- import_playbook: git/playbook.yml
- import_playbook: launch_scripts/playbook.yml
- import_playbook: mycli/playbook.yml
- import_playbook: tmux/playbook.yml
- import_playbook: tmuxp/playbook.yml
- import_playbook: vim/playbook.yml
- import_playbook: docker/playbook.yml
- import_playbook: kubernetes/playbook.yml
- import_playbook: node/playbook.yml
