set nocompatible
set number
hi LineNr ctermfg=238
set ruler

" improves macro performance by saving redraw till the end
set lazyredraw

" whitespace
set shiftwidth=4
set tabstop=4
set softtabstop=4
set noexpandtab
set autoindent

" backspace
set backspace=indent,eol,start

" search settings
set hlsearch
set incsearch
map <leader>nh :nohl<CR>

" show tabs
set list
set listchars=tab:\|·
hi SpecialKey ctermfg=236
nohl

filetype on
filetype plugin on
syntax on

" PHP whitespace settings
autocmd Filetype php setlocal noexpandtab
autocmd Filetype inc setlocal noexpandtab

" Colourscheme settings
set t_Co=256
set background=dark
let g:gruvbox_termcolors=256
let g:gruvbox_contrast_dark='hard'
let g:gruvbox_sign_column='bg0'
colors gruvbox

" always show the sign column (jumps annoyingly otherwise)
set signcolumn=yes

" Statusline settings
set laststatus=2
let g:airline_powerline_fonts = 1
let g:airline_theme='gruvbox'
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#tab_nr_type = 2
let g:airline#extensions#tabline#show_tab_nr = 1
let g:airline#extensions#whitespace#mixed_indent_algo = 1

" If we have phpcs in the project, use it
if filereadable("./core/vendor/bin/phpcs")
	let g:ale_php_phpcs_executable="./core/vendor/bin/phpcs"
elseif filereadable("./vendor/bin/phpcs")
	let g:ale_php_phpcs_executable="./vendor/bin/phpcs"
elseif
	let g:ale_php_phpcs_executable=""
endif

let g:ale_php_phpcs_standard='./ruleset.xml'

" space leader is the best leader
let mapleader = " "

" json prettyfying
map <leader>fJ :%!python -m json.tool<CR>

" sql prettyfying
map <leader>fS :%!sqlformat --reindent --keywords upper --identifiers lower -<CR>

" buffer and grep result navigation
map <leader>l :ls<CR>
map [b :bprev<CR>
map ]b :bnext<CR>
map [c :cprev<CR>
map ]c :cnext<CR>
map [l :lprev<CR>
map ]l :lnext<CR>

" different way of saving
map <leader>S :w<CR>
map <leader>s :w<CR>

" for moving around windows
map <leader>w <C-w>

" highlight col 80 to show long lines
execute "set colorcolumn=" . join([81, 121], ',')
hi ColorColumn ctermbg=236

set wildignore+=build/*

" csv shortcut
" map <leader>c /"\%(\_[^"]\+\\|""\)*"\\|[^",]*

" var dump snippet because I do this all the god damned time
map <leader>d o<CR>echo "<pre>";<CR>var_dump();<CR>echo "</pre>";<CR>die();<CR><C-[>kkk0f)

" emmet shortcut
map <leader>y <C-Y>

" easier shortcut for register access
map <leader>r "

" easier tab switching
map <leader>tl gt
map <leader>th gT
map <leader>te :tabedit
map <leader>t1 1gt
map <leader>t2 2gt
map <leader>t3 3gt
map <leader>t4 4gt
map <leader>t5 5gt
map <leader>t6 6gt
map <leader>t7 7gt
map <leader>t8 8gt
map <leader>t9 9gt

" toggle expandtab
map <leader>et :set expandtab<CR>
map <leader>eT :set noexpandtab<CR>

" change indentation type
map <leader>is :%retab<CR>
map <leader>it :%retab!<CR>

" php docblocks
let g:pdv_template_dir = $HOME ."/.vim/pack/plugins/start/pdv/templates_snip"
map <leader>pd :call pdv#DocumentWithSnip()<CR>

map <leader>pt :silent !phpctags -R<CR><CR>

" paste from system clipboard more efficiently
map <leader>cp :r !xclip -selection c -o<CR>
map <leader>cP :r !xclip -o<CR>
vmap <leader>cc :w !xclip -selection c -i<CR>
vmap <leader>cC :w !xclip -i<CR>
"nmap <leader>cc :set opfunc=CopyToClipboard<CR>g@

"function! CopyToClipboard(type)
"	execute "w !xclip -selection -c -i"
"endfunction
