---
- hosts: localhost
  tasks:
    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
      become: yes

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      become: yes

    - name: Update apt and install docker-ce
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes
      become: yes

    - name: Ensure ~/.local/bin directory exists
      file:
        path: "~/.local/bin"
        state: directory

    - name: Install docker-compose
      get_url:
        url : https://github.com/docker/compose/releases/download/1.26.0/docker-compose-Linux-x86_64
        dest: ~/.local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: Add my user to the docker group
      user:
        name: chris
        groups:
          - docker
        append: yes
      become: yes
